### ISSUE TITLE
Prefer game features to user features

### ISSUE THREAD

**Issue by aplarson** [jkopczyn/SideTable#1]
I'd prefer to see creating, tagging, and searching games moved ahead of the user interaction in phase 5

**Comment by jkopczyn** [comment]
I'll move tagging and searching up for sure, but creating is something that in theory most users would never do.

**Comment by aplarson** [comment]
Makes sense

**Comment by jkopczyn** [comment]
Would you suggest adding that earlier anyway?

**Comment by aplarson** [comment]
Depends on what "that" is here ;)

If it means creating games, I think it is worth making it available early (and allowing your guest user to do it); it is one of the canonical components of CRUD and shouldn't take too much work.

**Comment by jkopczyn** [comment]
Yes, that's what I meant, sorry. 
It's true that it should be easy, if I can find some way to work it into the site design smoothly. I'll look into it. (Directly copying from Goodreads would leave it difficult to even find the link.)

Also, README and phases updated to reflect revised plan.
